server:
  port: 8080

spring:
  datasource:
    username: root
    password: oTt9WJU4OnWYaN9O
    url: jdbc:mysql://121.37.1.52:3306/swkj?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      max-lifetime: 60000
      maximum-pool-size: 20
      idle-timeout: 30000
  mvc:
    static-path-pattern: /**
    view:
      prefix: /pages/
      suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:/usr/local/project/images
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lrj.pojo
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml



